"""persistent operational stores

Creates the full schema: identity and governance, sessions with runs and turns,
the pgvector knowledge base, ingestion jobs, trust, decision counters, tool
requests and security events.

Revision ID: 0001
Revises:
Create Date: 2026-10-03 15:26:55.382068

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector columns)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_counters",
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("allowed", sa.BigInteger(), nullable=False),
        sa.Column("denied", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("component", name=op.f("pk_decision_counters")),
    )
    op.create_table(
        "document_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("FILE", "URL", "DATABASE", "API", "MANUAL", name="source_type"),
            nullable=False,
        ),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column(
            "trust_level",
            sa.Enum("UNTRUSTED", "LOW", "MEDIUM", "HIGH", "VERIFIED", name="source_trust_level"),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_sources")),
    )
    op.create_index(op.f("ix_document_sources_name"), "document_sources", ["name"], unique=False)
    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_jobs")),
    )
    op.create_index(op.f("ix_ingest_jobs_stage"), "ingest_jobs", ["stage"], unique=False)
    op.create_index(op.f("ix_ingest_jobs_updated_at"), "ingest_jobs", ["updated_at"], unique=False)
    op.create_table(
        "security_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "PROMPT_INJECTION",
                "POLICY_VIOLATION",
                "TRUST_DEGRADATION",
                "TOOL_DENIED",
                "AUTH_FAILURE",
                "ANOMALY",
                name="security_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="security_severity"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=128), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_events")),
    )
    op.create_index(op.f("ix_security_events_actor"), "security_events", ["actor"], unique=False)
    op.create_index(
        op.f("ix_security_events_created_at"), "security_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_security_events_event_type"), "security_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_security_events_session_id"), "security_events", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_security_events_severity"), "security_events", ["severity"], unique=False
    )
    op.create_table(
        "tool_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("input_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="tool_risk_level"),
            nullable=False,
        ),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_definitions")),
    )
    op.create_index(op.f("ix_tool_definitions_name"), "tool_definitions", ["name"], unique=True)
    op.create_table(
        "tool_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "DENIED", "EXECUTED", "FAILED", name="tool_request_status"
            ),
            nullable=False,
        ),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("output_action", sa.String(length=16), nullable=True),
        sa.Column("redactions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_requests")),
    )
    op.create_index(op.f("ix_tool_requests_agent"), "tool_requests", ["agent"], unique=False)
    op.create_index(
        op.f("ix_tool_requests_requested_at"), "tool_requests", ["requested_at"], unique=False
    )
    op.create_index(
        op.f("ix_tool_requests_session_id"), "tool_requests", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_tool_requests_status"), "tool_requests", ["status"], unique=False)
    op.create_index(op.f("ix_tool_requests_tool"), "tool_requests", ["tool"], unique=False)
    op.create_table(
        "trust_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("AGENT", "SOURCE", "TOOL", name="trust_subject_type"),
            nullable=False,
        ),
        sa.Column("subject_key", sa.String(length=255), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("previous", sa.Float(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("UNTRUSTED", "LOW", "MEDIUM", "HIGH", "VERIFIED", name="trust_level"),
            nullable=False,
        ),
        sa.Column("signal", sa.String(length=64), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("assessed_by", sa.String(length=128), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trust_assessments")),
    )
    op.create_index(
        op.f("ix_trust_assessments_created_at"), "trust_assessments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_trust_assessments_subject_key"), "trust_assessments", ["subject_key"], unique=False
    )
    op.create_index(
        op.f("ix_trust_assessments_subject_type"),
        "trust_assessments",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "trust_scores",
        sa.Column(
            "subject_type",
            sa.Enum("AGENT", "SOURCE", "TOOL", name="trust_subject_type"),
            nullable=False,
        ),
        sa.Column("subject_key", sa.String(length=255), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("assessments", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("subject_type", "subject_key", name=op.f("pk_trust_scores")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "SECURITY_ANALYST", "AGENT", name="user_role"), nullable=False
        ),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", "DISABLED", name="agent_status"),
            nullable=False,
        ),
        sa.Column("trust_score", sa.Float(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_agents_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["document_sources.id"],
            name=op.f("fk_documents_source_id_document_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(op.f("ix_documents_source_id"), "documents", ["source_id"], unique=False)
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CLOSED", "TERMINATED", name="session_status"),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_agent_sessions_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agent_sessions_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_sessions")),
    )
    op.create_index(
        op.f("ix_agent_sessions_agent_id"), "agent_sessions", ["agent_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunk_doc_index"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("allowed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("blocked_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_domains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sensitive_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name=op.f("fk_policies_agent_id_agents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
    )
    op.create_index(op.f("ix_policies_name"), "policies", ["name"], unique=False)
    op.create_table(
        "agent_turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
            name=op.f("fk_agent_turns_session_id_agent_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_turns")),
    )
    op.create_index(op.f("ix_agent_turns_created_at"), "agent_turns", ["created_at"], unique=False)
    op.create_index(op.f("ix_agent_turns_session_id"), "agent_turns", ["session_id"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_embeddings_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
    )
    op.create_index(op.f("ix_embeddings_chunk_id"), "embeddings", ["chunk_id"], unique=True)
    op.create_table(
        "session_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_stage", sa.String(length=32), nullable=True),
        sa.Column("stages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
            name=op.f("fk_session_runs_session_id_agent_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_runs")),
        sa.UniqueConstraint("session_id", "request_id", name="uq_session_runs_request"),
    )
    op.create_index(
        op.f("ix_session_runs_session_id"), "session_runs", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_session_runs_status"), "session_runs", ["status"], unique=False)
    # ### end Alembic commands ###
    # Approximate nearest-neighbour index for cosine similarity search.
    op.execute(
        "CREATE INDEX ix_embeddings_vector_hnsw ON embeddings USING hnsw (vector vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_embeddings_vector_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_runs_status"), table_name="session_runs")
    op.drop_index(op.f("ix_session_runs_session_id"), table_name="session_runs")
    op.drop_table("session_runs")
    op.drop_index(op.f("ix_embeddings_chunk_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_agent_turns_session_id"), table_name="agent_turns")
    op.drop_index(op.f("ix_agent_turns_created_at"), table_name="agent_turns")
    op.drop_table("agent_turns")
    op.drop_index(op.f("ix_policies_name"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_agent_sessions_agent_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    op.drop_index(op.f("ix_documents_source_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("trust_scores")
    op.drop_index(op.f("ix_trust_assessments_subject_type"), table_name="trust_assessments")
    op.drop_index(op.f("ix_trust_assessments_subject_key"), table_name="trust_assessments")
    op.drop_index(op.f("ix_trust_assessments_created_at"), table_name="trust_assessments")
    op.drop_table("trust_assessments")
    op.drop_index(op.f("ix_tool_requests_tool"), table_name="tool_requests")
    op.drop_index(op.f("ix_tool_requests_status"), table_name="tool_requests")
    op.drop_index(op.f("ix_tool_requests_session_id"), table_name="tool_requests")
    op.drop_index(op.f("ix_tool_requests_requested_at"), table_name="tool_requests")
    op.drop_index(op.f("ix_tool_requests_agent"), table_name="tool_requests")
    op.drop_table("tool_requests")
    op.drop_index(op.f("ix_tool_definitions_name"), table_name="tool_definitions")
    op.drop_table("tool_definitions")
    op.drop_index(op.f("ix_security_events_severity"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_session_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_event_type"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_created_at"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_actor"), table_name="security_events")
    op.drop_table("security_events")
    op.drop_index(op.f("ix_ingest_jobs_updated_at"), table_name="ingest_jobs")
    op.drop_index(op.f("ix_ingest_jobs_stage"), table_name="ingest_jobs")
    op.drop_table("ingest_jobs")
    op.drop_index(op.f("ix_document_sources_name"), table_name="document_sources")
    op.drop_table("document_sources")
    op.drop_table("decision_counters")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS source_type")
    op.execute("DROP TYPE IF EXISTS source_trust_level")
    op.execute("DROP TYPE IF EXISTS security_event_type")
    op.execute("DROP TYPE IF EXISTS security_severity")
    op.execute("DROP TYPE IF EXISTS tool_risk_level")
    op.execute("DROP TYPE IF EXISTS tool_request_status")
    op.execute("DROP TYPE IF EXISTS trust_subject_type")
    op.execute("DROP TYPE IF EXISTS trust_level")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS agent_status")
    op.execute("DROP TYPE IF EXISTS session_status")
