"""shared rate limiter

One row per counted attempt, so tool-call and login limits hold across API workers.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 15:30:45.789039

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (Vector columns)
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_hits")),
    )
    op.create_index(op.f("ix_rate_limit_hits_at"), "rate_limit_hits", ["at"], unique=False)
    op.create_index(op.f("ix_rate_limit_hits_key"), "rate_limit_hits", ["key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rate_limit_hits_key"), table_name="rate_limit_hits")
    op.drop_index(op.f("ix_rate_limit_hits_at"), table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
