"""approvals and red-team runs

Human-approval columns on tool_requests; history table for red-team lab runs.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 23:23:25.753073

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401  (Vector columns)
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redteam_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redteam_runs'))
    )
    op.create_index(op.f('ix_redteam_runs_started_at'), 'redteam_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_redteam_runs_status'), 'redteam_runs', ['status'], unique=False)
    op.add_column('tool_requests', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tool_requests', sa.Column('reviewed_by', sa.String(length=64), nullable=True))
    op.add_column('tool_requests', sa.Column('review_note', sa.Text(), nullable=True))
    op.add_column('tool_requests', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_requests', 'reviewed_at')
    op.drop_column('tool_requests', 'review_note')
    op.drop_column('tool_requests', 'reviewed_by')
    op.drop_column('tool_requests', 'expires_at')
    op.drop_index(op.f('ix_redteam_runs_status'), table_name='redteam_runs')
    op.drop_index(op.f('ix_redteam_runs_started_at'), table_name='redteam_runs')
    op.drop_table('redteam_runs')
    # ### end Alembic commands ###
